name: '✨ Feature Request'
description: Suggest an idea or feature.
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a new idea or feature!
  - type: markdown
    attributes:
      value: 'Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Ensure your issue isn't already [reported](https://github.com/z3rofunk/snippers/issues?utf8=%E2%9C%93&q=is%3Aissue).
        - Ensure it isn't already fixed in the latest Snippers version.
  - type: textarea
    id: description
    attributes:
      label: |
        - Is your feature request related to a problem?
        - If not, feel free to describe any idea or feature you'd like to see implemented.
      description: A clear and concise description of the problem or idea/feature.
      placeholder: |
        - I'm always frustrated when [...]
        - Or
        - I would like to see..
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want/expected to happen.
    validations:
      required: false
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: |
        Briefly summarize any alternative solutions or workarounds you've explored.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Notes or Insights
      description: |
        - Mention anything else important for understanding the problem, feature or idea.
        - Feel free to include any relevant details or insights you believe would be helpful.
        - If applicable, include any screenshots to help explain.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ----

        # Enviroment
  - type: input
    id: snippers-version
    attributes:
      label: 'Snippers Version'
      placeholder: 'e.g. 0.2.0'
  - type: input
    id: node-version
    attributes:
      label: 'Node.js Version'
      description: 'node --version'
      placeholder: 'e.g. 13.0.1'
    validations:
      required: false
